---
###################
# Ansible options
###################
###Added or changed by Hamed and Soheil
#added
huge_pages: "16"
huge_page_size: "1G"
huge_pages_auto_config: "false"

dpdk_bridge_name: "br-dpdk"

ovs_memory_channels: "4"
ovs_socket_memory_per_numa: "1024"

pmd_cpu_per_numa_isolated: "2"

dpdk_alloc_mem: "2048"

#changed
dpdk_tunnel_interface: "{{ tunnel_interface }}"
# Adding the mentioned configs to https://github.com/openstack/kolla-ansible/blob/stable/xena/ansible/group_vars/all.yml when you want integrate my code by kolla-ansible
