---
ovs_bridge_mappings: "{% for bridge in neutron_bridge_name.split(',') %}physnet{{ loop.index0 + 1 }}:{{ bridge }}{% if not loop.last %},{% endif %}{% endfor %}"
ovs_port_mappings: "{% for bridge in neutron_bridge_name.split(',') %} {{ neutron_external_interface.split(',')[loop.index0] }}:{{ bridge }}{% if not loop.last %},{% endif %}{% endfor %}"

ovs_dpdk_tunnel_interface_network: "{{ hostvars[inventory_hostname].ansible_facts[dpdk_tunnel_interface]['ipv4']['network']}}/{{hostvars[inventory_hostname].ansible_facts[dpdk_tunnel_interface]['ipv4']['netmask'] }}"
ovs_dpdk_tunnel_interface_cidr: "{{ dpdk_tunnel_interface_address }}/{{ ovs_dpdk_tunnel_interface_network | ipaddr('prefix') }}"
ovs_dpdk_tunnel_interface: "{{ dpdk_tunnel_interface }}"

ovs_dpdk_bridge_name: "{{ dpdk_bridge_name }}"

ovs_dpdk_mem_channels: "{{ ovs_memory_channels }}"
ovs_dpdk_socket_mem_per_numa: "{{ ovs_socket_memory_per_numa }}"
#ovs_dpdk_socket_mem_per_numa: "{% for numa in numaList %}{{ ovs_socket_memory }}{% if not loop.last %},{% endif %}{% endfor %}"
ovs_dpdk_alloc_mem: "{{ dpdk_alloc_mem }}"

ovs_dpdk_conf_dir: /etc/kolla/ovs_dpdk

ovs_dpdk_hugepage_mountpoint: /dev/hugepages
ovs_dpdk_hugepage_auto_config: "{{ huge_page_auto_config }}"
ovs_dpdk_hugepage_size: "{{ huge_page_size }}"
#ovs_dpdk_hugepages: "{{ huge_pages }}"
ovs_dpdk_hugepages: "{% if (ovs_dpdk_hugepage_auto_config | bool) %}{{ ((ansible_facts.memtotal_mb / 1024) * 0.8) | int }}{% else %}{{ huge_pages }}{% endif %}"

ovs_dpdk_interface_driver: "{{ dpdk_interface_driver }}"

pmd_cpu_per_numa: "{{ pmd_cpu_per_numa_isolated }}"