---
- import_tasks: install_service.yml
- import_tasks: prepare_host.yml
- import_tasks: update_grub.yml
- import_tasks: ovs-configuration.yml
- name: Flush Handlers
  meta: flush_handlers


###### last Code #####
# - import_tasks: config.yml
# - import_tasks: check-containers.yml
# - name: Flush Handlers
#   meta: flush_handlers