---
- name: Restart openvswitch-switch service
  become: True 
  service: 
    name: openvswitch-switch
    state: restarted
    enabled: true

- name: Update grub
  become: True 
  command:
    cmd: >
      /usr/sbin/update-grub
  notify: "Reboot host and wait for it to restart"

- name: Reboot host and wait for it to restart
  become: true
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
    notify: "Restart service ovs-dpdkctl"

- name: Restart service ovs-dpdkctl
  become: true
  service: 
    name: ovs-dpdkctl
    state: restarted
    enabled: true